# Generated by Django 3.2.16 on 2022-11-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='projects',
        ),
    ]
